
# library(shiny)
library(rgdal)
library(raster)
library(dplyr)
library(leaflet)
# library(RColorBrewer)
# library(sp)
# library(RCurl)
# library(devtools)
library(shinyjs)
# library(V8)
# library(pbapply)
# library(plotly)
# library(importr)
library(lubridate)
library(dygraphs)
library(DT)


# devtools::install_github("rstudio/shinydashboard")
library(shinydashboard)

jscode <- "shinyjs.refresh = function() { history.go(0); }"

ui <- dashboardPage(skin = "blue",
                    dashboardHeader(title = "Monitoring data"),
                    
                    dashboardSidebar(
                      width = 250,
                      paste("Time:",Sys.time()),
                      sidebarMenu(
                        
                       
                        # fileInput('files', 'choose csv File (from databases)', multiple = TRUE,
                        #           accept = c(".csv")),
                        
                        selectInput("database", "Network",                  
                                    c("AURN" = "archive", 
                                      "WALES" = "Waq",
                                      "AQENGLAND" = "aqengland",
                                      "KENT" = "kent",
                                      "Nothern Ireland" = "niarc",
                                      "North Lincs" = "nlincs",
                                      "Scotland" = "scotarc"),
                                       selected = "archive"),
                      
                        conditionalPanel(
                          condition = "input.database == 'archive'",
                          selectInput("site_archive", "Site", c("Aberdeen"="abd",
                                                        "Aberdeen Union Street Roadside"="abd7",
                                                        "Aberdeen Wellington Road"="abd8",
                                                        "Armagh Roadside"="arm6",
                                                        "Aston Hill"="ah",
                                                        "Auchencorth Moss"="acth",
                                                        "Ballymena Ballykeel"="balm",
                                                        "Barnsley Gawber"="bar3",
                                                        "Barnstaple A39"="bple",
                                                        "Bath Roadside"="bath",
                                                        "Belfast Centre"="bel2",
                                                        "Belfast Stockman's Lane"="bel1",
                                                        "Billingham"="bil",
                                                        "Birkenhead Borough Road"="bbrd",
                                                        "Birmingham A4540 Roadside"="birr",
                                                        "Birmingham Acocks Green"="agrn",
                                                        "Birmingham Tyburn"="bir1",
                                                        "Blackburn Accrington Road"="blar",
                                                        "Blackpool Marton"="blc2",
                                                        "Bottesford"="bot",
                                                        "Bournemouth"="born",
                                                        "Bradford Mayo Avenue"="bdma",
                                                        "Brighton Preston Park"="brt3",
                                                        "Bristol St Paul's"="brs8",
                                                        "Bury Whitefield Roadside"="burw",
                                                        "Bush Estate"="bush",
                                                        "Cambridge Roadside"="cam",
                                                        "Camden Kerbside"="ca1",
                                                        "Cannock A5190 Roadside"="cank",
                                                        "Canterbury"="cant",
                                                        "Cardiff Centre"="card",
                                                        "Carlisle Roadside"="carl",
                                                        "Charlton Mackrell"="mack",
                                                        "Chatham Roadside"="chat",
                                                        "Chepstow A48"="chp",
                                                        "Chesterfield Loundsley Green"="chlg",
                                                        "Chesterfield Roadside"="chs7",
                                                        "Chilbolton Observatory"="chbo",
                                                        "Christchurch Barrack Road"="chbr",
                                                        "Coventry Allesley"="coal",
                                                        "Cwmbran"="cwmb",
                                                        "Derry Rosemount"="derr",
                                                        "Doncaster A630 Cleveland Street"="dcst",
                                                        "Dumbarton Roadside"="dumb",
                                                        "Dumfries"="dumf",
                                                        "Ealing Horn Lane"="ea8",
                                                        "Eastbourne"="eb",
                                                        "Edinburgh St Leonards"="ed3",
                                                        "Eskdalemuir"="esk",
                                                        "Exeter Roadside"="ex",
                                                        "Fort William"="fw",
                                                        "Glasgow Great Western Road"="ggwr",
                                                        "Glasgow High Street"="ghsr",
                                                        "Glasgow Kerbside"="gla4",
                                                        "Glasgow Townhead"="glkp",
                                                        "Glazebury"="glaz",
                                                        "Grangemouth"="gran",
                                                        "Grangemouth Moray"="gra2",
                                                        "Great Dun Fell"="gdf",
                                                        "Greenock A8 Roadside"="gka8",
                                                        "Hafod-yr-ynys Roadside"="cae6",
                                                        "Haringey Roadside"="hg1",
                                                        "High Muffles"="hm",
                                                        "Honiton"="honi",
                                                        "Horley"="hore",
                                                        "Hull Freetown"="hul2",
                                                        "Hull Holderness Road"="hulr",
                                                        "Inverness"="inv2",
                                                        "Ladybower"="lb",
                                                        "Leamington Spa"="leam",
                                                        "Leamington Spa Rugby Road"="lear",
                                                        "Leeds Centre"="leed",
                                                        "Leeds Headingley Kerbside"="led6",
                                                        "Leicester A594 Roadside"="leir",
                                                        "Leicester University"="lecu",
                                                        "Leominster"="leom",
                                                        "Lerwick"="lerw",
                                                        "Lincoln Canwick Rd."="lin3",
                                                        "Liverpool Queen's Drive Roadside"="lv6",
                                                        "Liverpool Speke"="lvp",
                                                        "London Bexley"="bex",
                                                        "London Bloomsbury"="cll2",
                                                        "London Eltham"="lon6",
                                                        "London Haringey Priory Park South"="hg4",
                                                        "London Harlington"="hrl",
                                                        "London Harrow Stanmore"="hr3",
                                                        "London Hillingdon"="hil",
                                                        "London Marylebone Road"="my1",
                                                        "London N. Kensington"="kc1",
                                                        "London Teddington"="ted",
                                                        "London Teddington Bushy Park"="ted2",
                                                        "London Westminster"="hors",
                                                        "Lough Navar"="ln",
                                                        "Lullington Heath"="lh",
                                                        "Luton A505 Roadside"="lutr",
                                                        "Mace Head"="mh",
                                                        "Manchester Piccadilly"="man3",
                                                        "Manchester Sharston"="mahg",
                                                        "Market Harborough"="mkth",
                                                        "Middlesbrough"="mid",
                                                        "Narberth"="pemb",
                                                        "Newcastle Centre"="newc",
                                                        "Newcastle Cradlewell Roadside"="nca3",
                                                        "Newport"="npt3",
                                                        "Northampton Kingsthorpe"="ntn3",
                                                        "Norwich Lakenfields"="no12",
                                                        "Nottingham Centre"="nott",
                                                        "Nottingham Western Boulevard"="nwbv",
                                                        "Oldbury Birmingham Road"="bold",
                                                        "Oxford Centre Roadside"="ox",
                                                        "Oxford St Ebbes"="ox8",
                                                        "Peebles"="peeb",
                                                        "Plymouth Centre"="plym",
                                                        "Port Talbot Margam"="pt4",
                                                        "Portsmouth"="pmth",
                                                        "Preston"="pres",
                                                        "Reading London Rd."="rea5",
                                                        "Reading New Town"="rea1",
                                                        "Rochester Stoke"="roch",
                                                        "Salford Eccles"="eccl",
                                                        "Saltash Callington Road"="sash",
                                                        "Sandy Roadside"="sdy",
                                                        "Scunthorpe Town"="scn2",
                                                        "Shaw Crompton Way"="cw",
                                                        "Sheffield Barnsley Road"="shbr",
                                                        "Sheffield Devonshire Green"="shdg",
                                                        "Sheffield Tinsley"="she",
                                                        "Sibton"="sib",
                                                        "Southampton A33"="sa33",
                                                        "Southampton Centre"="sout",
                                                        "Southend-on-Sea"="send",
                                                        "Southwark A2 Old Kent Road"="sk5",
                                                        "St Osyth"="osy",
                                                        "Stanford-le-Hope Roadside"="hope",
                                                        "Stockton-on-Tees A1305 Roadside"="sotr",
                                                        "Stockton-on-Tees Eaglescliffe"="eagl",
                                                        "Stoke-on-Trent A50 Roadside"="stkr",
                                                        "Stoke-on-Trent Centre"="stok",
                                                        "Storrington Roadside"="stor",
                                                        "Strathvaich"="sv",
                                                        "Sunderland Silksworth"="sun2",
                                                        "Sunderland Wessington Way"="sunr",
                                                        "Swansea Roadside"="swa1",
                                                        "Thurrock"="thur",
                                                        "Tower Hamlets Roadside"="th2",
                                                        "Walsall Woodlands"="wal4",
                                                        "Warrington"="war",
                                                        "Weybourne"="weyb",
                                                        "Wicken Fen"="wfen",
                                                        "Widnes Milton Road"="wsmr",
                                                        "Wigan Centre"="wig5",
                                                        "Wirral Tranmere"="tran",
                                                        "Wrexham"="wrex",
                                                        "Yarner Wood"="yw",
                                                        "York Bootham"="yk10",
                                                        "York Fishergate"="yk11"))),
                        
                        conditionalPanel(
                          condition = "input.database == 'Waq'",
                          selectInput("site_Waq", "Site", c("Anglesey Brynteg"="ang5",
                                                            "Anglesey Felin Cafnan"="an10",
                                                            "Anglesey Llynfaes"="ang2",
                                                            "Aston Hill"="ah",
                                                            "Caerphilly Blackwood High Street"="cae5",
                                                            "Caerphilly Fochriw"="cae8",
                                                            "Caerphilly White Street"="cae4",
                                                            "Cardiff Centre"="card",
                                                            "Chepstow A48"="chep",
                                                            "Cimla Road / Victoria Gardens"="nth1",
                                                            "Cwmbran"="cwmb",
                                                            "Hafod-yr-ynys Roadside"="cae6",
                                                            "Marchlyn Mawr"="mawr",
                                                            "Nantgarw Road"="cae7",
                                                            "Narberth"="pemb",
                                                            "Newport M4 Junction 25"="npt4",
                                                            "Newport St Julians Comp School"="npt1",
                                                            "Port Talbot Margam"="pt4",
                                                            "Port Talbot Prince Street (FDMS only)"="mmf6a",
                                                            "Port Talbot Prince Street 2"="pt11",
                                                            "Rhondda-Cynon-Taf Broadway"="rhd4",
                                                            "Rhondda-Cynon-Taf Nantgarw"="rhd2",
                                                            "Rhondda Mountain Ash"="rhd8",
                                                            "Rhondda Pontypridd Gelliwastad Rd"="rhd6",
                                                            "Swansea Cwm Level Park"="swa9",
                                                            "Swansea Hafod DOAS"="swa7",
                                                            "Swansea Morriston Roadside"="swa5",
                                                            "Swansea Roadside"="swa1",
                                                            "Swansea St Thomas DOAS"="swa8",
                                                            "Swansea Station Court High Street"="sw10",
                                                            "Twynyrodyn"="twyn",
                                                            "V Glamorgan Windsor Road Penarth"="glm8",
                                                            "Wrexham"="wrex"))),
                        
                        conditionalPanel(
                          condition = "input.database == 'aqengland'",
                          selectInput("site_aqengland", "Site", c("Aylesbury Walton Street 2"="ay1",
                                                                  "Barnsley A628 Pogmoor Roadside"="bar6",
                                                                  "Barnsley A635 Kendray Roadside"="bar9",
                                                                  "Barnsley Monckton"="ba10",
                                                                  "Birmingham Airport 2"="bai2",
                                                                  "Birmingham Fore Street"="bifs",
                                                                  "Bolton College"="bol2",
                                                                  "Bradford-on-Avon= Masons Lane"="wil1",
                                                                  "Bradford Manchester Road"="brd5",
                                                                  "Bradford Shipley Airedale Road"="brd6",
                                                                  "Bromsgrove Lickey End"="brm1",
                                                                  "Bury Prestwich"="bur2",
                                                                  "Bury Radcliffe"="bur1",
                                                                  "Calderdale Romon 2"="cald",
                                                                  "Calderdale Romon 4"="cal1",
                                                                  "Calne London Road"="wil8",
                                                                  "Calne= New Road 2"="wil5",
                                                                  "Cam Road"="new2",
                                                                  "Cambridge Gonville Place"="cam3",
                                                                  "Cambridge Montague Road"="cam5",
                                                                  "Cambridge Newmarket Road"="cam4",
                                                                  "Cambridge Parker Street"="cam1",
                                                                  "Camden Shaftesbury Avenue"="cd3",
                                                                  "Canterbury PM10"="can2",
                                                                  "Carlisle Stanwix Bank"="crl2",
                                                                  "Charnwood Baxter Gate"="char",
                                                                  "Darlington St Cuthbert's Way"="darl",
                                                                  "Devizes= Sidmouth Street"="wil3",
                                                                  "Doncaster Carr House Road"="dchr",
                                                                  "Doncaster Warmsworth Grosvenor Ter"="don1",
                                                                  "East Midlands Airport"="em1",
                                                                  "Ewell High Street"="ewe2",
                                                                  "Fareham Portland Street"="far2",
                                                                  "Gateshead A1 Dunston"="ga1",
                                                                  "Gateshead Bottle Bank"="ga2",
                                                                  "Gateshead Lychgate Court"="ga3",
                                                                  "Gatwick LGW3"="lgw3",
                                                                  "Girton Road"="girt",
                                                                  "Gosport Road"="far1",
                                                                  "Heathrow Green Gates"="t55",
                                                                  "Heathrow LHR2"="lhr2",
                                                                  "Heathrow Oaks Road"="t54",
                                                                  "Henley"="hen",
                                                                  "Hillingdon 1 - South Ruislip"="hi1",
                                                                  "Hounslow Brentford"="hs5",
                                                                  "Hounslow Chiswick"="hs4",
                                                                  "Hounslow Cranford"="hs2",
                                                                  "Hounslow Feltham"="hs9",
                                                                  "Hounslow Gunnersbury"="hs8",
                                                                  "Hounslow Hatton Cross"="hs7",
                                                                  "Hounslow Heston"="hs6",
                                                                  "Ipswich Chevallier Street"="ips3",
                                                                  "King's Lynn Southgates"="kly8",
                                                                  "London Barnet Chalgrove School"="bn2",
                                                                  "London Hillingdon Harmondsworth"="hil1",
                                                                  "London Hillingdon Harmondsworth Os"="hil4",
                                                                  "London Hillingdon Hayes"="hil5",
                                                                  "London Hillingdon Oxford Avenue"="hi3",
                                                                  "Maidenhead Roadside"="mw1",
                                                                  "Manchester Oxford Road"="man1",
                                                                  "Manchester Piccadilly LA"="man7",
                                                                  "Marlborough London Road"="wil7",
                                                                  "Newcastle-under-Lyme Queens Gardens"="nul1",
                                                                  "Newcastle Pilgrim Street"="nca4",
                                                                  "North Lincs Amvale"="amvl",
                                                                  "North Lincs Appleby Village"="apb2",
                                                                  "North Lincs Killingholme"="kilh",
                                                                  "North Lincs Redbourne"="rebn",
                                                                  "North Lincs Santon"="sant",
                                                                  "North Lincs Santon Dawes Lane"="dawe",
                                                                  "North Lincs South Ferriby"="sfer",
                                                                  "North Lincs Station Road"="stat",
                                                                  "North Warwickshire Coleshill"="cole",
                                                                  "Northumberland Blyth Library"="nmb1",
                                                                  "Northumberland Cowpen Road"="nmb2",
                                                                  "Norwich Castle Meadow"="no11",
                                                                  "Oxford High St"="ox6",
                                                                  "Oxford St Ebbes (Cal Club)"="ox3",
                                                                  "Reading Caversham Road"="rea2",
                                                                  "Reading Oxford Road"="rea4",
                                                                  "Redcar Dormanstown"="red3",
                                                                  "Rotherham Bradgate"="rot4",
                                                                  "S Cambs Impington"="imp",
                                                                  "S Cambs Orchard Park School"="orch",
                                                                  "Salford M60"="m60",
                                                                  "Salisbury= Exeter Street"="wil4",
                                                                  "Scunthorpe East Common Lane"="scn6",
                                                                  "Scunthorpe Lincoln Gardens"="scn5",
                                                                  "Sefton Princess Way"="sef8",
                                                                  "Shaw Crompton Way "="cw",
                                                                  "Sipson"="sips",
                                                                  "Slough Chalvey"="slh7",
                                                                  "Slough Colnbrook"="slh3",
                                                                  "Slough Colnbrook Osiris"="slh6",
                                                                  "Slough Lakeside 1 Osiris"="slh5",
                                                                  "Slough Lakeside 2"="slh8",
                                                                  "Slough Lakeside 2 Osiris"="slh9",
                                                                  "Slough Town Centre A4"="slh4",
                                                                  "South Bucks Gerrards Cross"="gx",
                                                                  "South Holland Westmere School"="shol",
                                                                  "South Normanton"="norm",
                                                                  "South Oxfordshire Wallingford"="sox3",
                                                                  "Spalding Monkhouse School"="monk",
                                                                  "Stansted 3"="sta3",
                                                                  "Stansted 4"="sta4",
                                                                  "Stockport Cheadle A34"="stk7",
                                                                  "Stockport Hazel Grove"="stk5",
                                                                  "Stoke on Trent Joiners Sqaure"="sto3",
                                                                  "Stoke on Trent Meir"="sto4",
                                                                  "Suffolk Coastal Woodbridge 2"="scw2",
                                                                  "Sunderland Silksworth (CC)"="sun2",
                                                                  "Sunderland Trimdon Street"="sun4",
                                                                  "Tally Ho"="bn1",
                                                                  "Tameside Mottram Moor"="tam1",
                                                                  "Tameside Two Trees School"="tame",
                                                                  "Thurrock Tilbury"="tk4",
                                                                  "Tichborne Way"="gos1",
                                                                  "Trafford"="traf",
                                                                  "Trafford A56"="trf2",
                                                                  "Wakefield"="wake",
                                                                  "Wakefield Horbury Road"="wak2",
                                                                  "Wallingford"="wd1",
                                                                  "Waltham Crooked Billet"="wl4",
                                                                  "Waltham Forest Dawlish Rd"="wl1",
                                                                  "Waltham Forest Leyton"="wl5",
                                                                  "Warwick Jury Street"="warw",
                                                                  "Watlington"="wat",
                                                                  "Widnes Marzahn Way"="wid2",
                                                                  "Widnes Milton Road"="wid1",
                                                                  "Wigan Centre PM10"="wig7",
                                                                  "Wren Close"="new3",
                                                                  "Wycombe Abbey 4"="wya4",
                                                                  "Wycombe Stokenchurch"="wsto",
                                                                  "York Bootham"="yk10",
                                                                  "York Fishergate"="yk11",
                                                                  "York Fulford Road"="yk16",
                                                                  "York Gillygate"="yk7",
                                                                  "York Heworth Green"="yk13",
                                                                  "York Holgate"="yk8",
                                                                  "York Lawrence Street"="yk9",
                                                                  "York Nunnery Lane"="yk15",
                                                                  "York Plantation Drive"="yk018"))),
                        
                        conditionalPanel(
                          condition = "input.database == 'kent'",
                          selectInput("site_kent", "Site", c("Canterbury"="cant",
                                                             "Canterbury Military Road"="zy3",
                                                             "Chatham Roadside"="zc1",
                                                             "Dartford Bean Interchange Roadside"="zr3",
                                                             "Dartford St Clements Roadside"="zr1",
                                                             "Dartford Town Centre Roadside"="zr2",
                                                             "Dover Centre Roadside"="zd2",
                                                             "Gravesham A2 Roadside"="zg2",
                                                             "Gravesham Industrial Background"="zg3",
                                                             "London Bexley"="bex",
                                                             "Maidstone Rural"="zm3",
                                                             "Rochester Stoke"="roch",
                                                             "Sevenoaks 2"="zv1",
                                                             "Sevenoaks roadside"="zv2",
                                                             "Stanford-le-Hope Roadside"="hope",
                                                             "Strood High Street"="strd",
                                                             "Swale Canterbury Road"="zw7",
                                                             "Swale Newington 3"="zw6",
                                                             "Swale Ospringe Roadside 2"="zw3",
                                                             "Swale St Pauls Street"="zw8",
                                                             "Thanet Birchington Roadside"="zh5",
                                                             "Thanet Ramsgate Roadside"="zh4",
                                                             "Thurrock"="thur",
                                                             "Tonbridge Roadside 2"="zt5",
                                                             "Tunbridge Wells A26 Roadside"="zt4"))),
                        
                        conditionalPanel(
                          condition = "input.database == 'niarc'",
                          selectInput("site_niarc", "Site", c("Armagh Lonsdale Road"="arm5",
                                                              "Ballymena Ballykeel"="baly",
                                                              "Belfast Centre"="bel2",
                                                              "Belfast Newtownards Road"="bel5",
                                                              "Belfast Ormeau Road"="bel0",
                                                              "Belfast Stockman's Lane"="bel1",
                                                              "Belfast Westlink Roden Street"="be2",
                                                              "Castlereagh Dundonald"="cas3",
                                                              "Derry Dale's Corner"="der4",
                                                              "Derry Rosemount"="derr",
                                                              "Downpatrick Roadside"="dpk1",
                                                              "Limavady Dungiven"="lvd2",
                                                              "Lisburn Dunmurry Seymour Hill"="lis5",
                                                              "Lough Navar"="ln",
                                                              "Newry Canal Street"="nwy5",
                                                              "Newtownabbey Antrim Road"="nwt5",
                                                              "North Down Holywood A2"="nd2",
                                                              "Strabane Springhill Park"="sban"))),
                         
                        conditionalPanel(
                          condition = "input.database == 'nlincs'",
                          selectInput("site_nlincs", "Site", c("Amvale"="amvl","Amvale Osiris"="amv2",
                                                        "North Lincs Appleby Village"="apb2",
                                                        "North Lincs Barton"="bart",
                                                        "North Lincs Barton Holydyke"="nl27",
                                                        "North Lincs Brigg Barnard Avenue"="nl21",
                                                        "North Lincs Brigg Hewson House (Background)"="nl22",
                                                        "North Lincs Brigg Hewson House (Roadside)"="nl23",
                                                        "North Lincs Brigg Wrawby Road"="nl24",
                                                        "North Lincs Crowle"="crow",
                                                        "North Lincs Epworth Belton Road"="nl04",
                                                        "North Lincs High Street East"="hse1",
                                                        "North Lincs Keadby Bridge A18"="nl05",
                                                        "North Lincs Killingholme Humber Road"="nl25",
                                                        "North Lincs Killingholme Roadside"="soki",
                                                        "North Lincs Killingholme School"="kilh",
                                                        "North Lincs Lakeside"="lake",
                                                        "North Lincs North Killingholme St Crispins Close"="nl26",
                                                        "North Lincs Santon"="sant",
                                                        "North Lincs Santon Dawes Lane"="dawe",
                                                        "North Lincs South Ferriby"="sfer",
                                                        "North Lincs Tarmac"="tarm",
                                                        "Redbourne Club"="rebn",
                                                        "Scunthorpe A1077 Orbital Road"="nl03",
                                                        "Scunthorpe Ashby Lodge Pub"="nl20",
                                                        "Scunthorpe Ashby Road"="nl11",
                                                        "Scunthorpe Ashby Road pub car park"="nl14",
                                                        "Scunthorpe Ashby Road/Brumby Street"="nl15",
                                                        "Scunthorpe Britannia Corner Oswald Rd"="nl09",
                                                        "Scunthorpe Doncaster Rd/Hilton Ave"="nl06",
                                                        "Scunthorpe Doncaster Rd/Royal Hotel"="nl08",
                                                        "Scunthorpe Dudley Road/Queensway"="nl18",
                                                        "Scunthorpe East Common Lane"="scn6",
                                                        "Scunthorpe Frodingham Road"="nl01",
                                                        "Scunthorpe Lakeside Parkway"="nl19",
                                                        "Scunthorpe Lloyds Ave/Ashby Rd"="nl13",
                                                        "Scunthorpe Lloyds Ave/Glover Rd"="nl12",
                                                        "Scunthorpe Normanby Road"="nl02",
                                                        "Scunthorpe Old Brumby/East Common Ln/Queensway"="nl16",
                                                        "Scunthorpe Oswald Road"="nl10",
                                                        "Scunthorpe Scotter Road"="nl07",
                                                        "Scunthorpe Station Rd/Brigg Rd"="nl28",
                                                        "Scunthorpe Town (Rowland Road)"="scn2",
                                                        "Scunthorpe Town (TEOM only)"="sc10",
                                                        "Scunthorpe Town 30"="nl30",
                                                        "Scunthorpe Town 31"="nl31",
                                                        "Scunthorpe Town 32"="nl32"))),
                        
                        conditionalPanel(
                          condition = "input.database == 'scotarc'",
                          selectInput("site_scotarc", "Site", c("Aberdeen Anderson Dr"="abd1",
                                                                "Aberdeen Errol Place"="abd",
                                                                "Aberdeen King Street"="ad1",
                                                                "Aberdeen Market Street 2"="abd0",
                                                                "Aberdeen Union Street Roadside"="abd3",
                                                                "Aberdeen Wellington Road"="abd8",
                                                                "Alloa A907"="alo2",
                                                                "Auchencorth Moss"="acth",
                                                                "Bush Estate"="bush",
                                                                "Dumfries"="dumf",
                                                                "Dundee Broughty Ferry Road"="dun4",
                                                                "Dundee Lochee Road"="dun6",
                                                                "Dundee Mains Loan"="dun1",
                                                                "Dundee Meadowside"="dunm",
                                                                "Dundee Seagate"="dun5",
                                                                "Dundee Whitehall Street"="dun7",
                                                                "E Ayrshire Kilmarnock St Marnock St"="marn",
                                                                "East Dunbartonshire Bearsden"="edb2",
                                                                "East Dunbartonshire Bishopbriggs"="edb1",
                                                                "East Dunbartonshire Kirkintilloch"="edb3",
                                                                "East Dunbartonshire Milngavie "="edb4",
                                                                "East Lothian Musselburgh N High St"="muss",
                                                                "Edinburgh Currie"="ed11",
                                                                "Edinburgh Glasgow Road"="ed10",
                                                                "Edinburgh Gorgie Road"="ed5",
                                                                "Edinburgh Queensferry Road"="ed9",
                                                                "Edinburgh Salamander St"="ed8",
                                                                "Edinburgh St John's Road"="ed1",
                                                                "Edinburgh St Leonards"="ed3",
                                                                "Eskdalemuir"="esk",
                                                                "Falkirk Banknock"="fal7",
                                                                "Falkirk Grangemouth MC"="falk",
                                                                "Falkirk Haggs"="fal5",
                                                                "Falkirk Hope St"="fal3",
                                                                "Falkirk West Bridge Street"="fal6",
                                                                "Fife Cupar"="cupa",
                                                                "Fife Dunfermline"="dunf",
                                                                "Fife Kirkcaldy"="kir",
                                                                "Fife Rosyth"="rosy",
                                                                "Fort William"="fw",
                                                                "Glasgow Anderston"="gla5",
                                                                "Glasgow Burgher St."="gl6",
                                                                "Glasgow Byres Road"="gla6",
                                                                "Glasgow Dumbarton Road"="gl9",
                                                                "Glasgow Great Western Road"="ggwr",
                                                                "Glasgow High Street"="ghsr",
                                                                "Glasgow Kerbside"="gla4",
                                                                "Glasgow Townhead"="glkp",
                                                                "Glasgow Waulkmillglen Reservoir"="gla7",
                                                                "Grangemouth"="gran",
                                                                "Grangemouth Moray"="gra2",
                                                                "Inverclyde Greenock A8"="inc2",
                                                                "Inverness"="inv2",
                                                                "Lerwick"="lerw",
                                                                "N Lanarkshire Chapelhall"="nl3",
                                                                "N Lanarkshire Coatbridge Whifflet"="nl1",
                                                                "N Lanarkshire Croy"="nl4",
                                                                "N Lanarkshire Moodiesburn"="nl9",
                                                                "N Lanarkshire Motherwell"="nl6",
                                                                "N Lanarkshire Shawhead Coatbridge"="nl7",
                                                                "North Ayrshire Irvine High St"="irv",
                                                                "North Lanarkshire Kirkshaw"="nl11",
                                                                "Paisley Gordon Street"="pai3",
                                                                "Peebles"="peeb",
                                                                "Perth Atholl Street"="pet2",
                                                                "Perth Crieff"="pet1",
                                                                "Perth High Street"="peth",
                                                                "Renfrew Cockels Loan"="ren1",
                                                                "South Ayrshire Ayr Harbour"="harb",
                                                                "South Ayrshire Ayr High St"="ayr",
                                                                "South Lanarkshire Cambuslang"="sl07",
                                                                "South Lanarkshire East Kilbride"="ek0",
                                                                "South Lanarkshire Hamilton"="sl05",
                                                                "South Lanarkshire Lanark"="sl03",
                                                                "South Lanarkshire Rutherglen"="sl04",
                                                                "South Lanarkshire Uddingston"="sl06",
                                                                "Stirling Craig's Roundabout"="strl",
                                                                "Strath Vaich"="sv",
                                                                "West Dunbartonshire Clydebank"="wdb3",
                                                                "West Dunbartonshire Glasgow Road"="wdb4",
                                                                "West Lothian Broxburn"="brx",
                                                                "West Lothian Linlithgow High Street 2"="wlc1",
                                                                "West Lothian Newton"="wln4"))),
                      
                        
                        selectInput(
                          "variable", "Pollutant",
                          c(
                            "NO2" = "no2", "O3" = "o3",
                            "Grav. Equiv. PM10" = "ge10",
                            "Grav. PM10" = "gr10",
                             "PM2.5" = "pm25", "Grav. PM2.5" = "gr25",
                            "V10" = "v10", "V25" = "v25"
                          )
                        ),
                        

                        
                        dateInput("start", "Start Day",
                                  value = "2016-10-01", format = "yyyy-mm-dd"),

                        dateInput("end", "End Day",
                                  value = "2016-10-03", format = "yyyy-mm-dd"),
                      #  br(),
                      
                      

                        fluidRow(
                          column (3,offset = 1,
                                  actionButton("goButton", strong("Process data"), icon("cog", lib = "glyphicon"), 
                                               style="color: #000000; background-color: #ffff7f ; border-color: #ffff7f"), # width = 150
                                  DT::dataTableOutput('contents')
                          )),

                        
                        menuItem("Statistics", tabName = "Stats", icon = icon("th")),
                        menuItem("Map", tabName = "MAP", icon = icon("th")),
                        # menuItem("Additional stuff", tabName = "Add_Stuff", icon = icon("th")),
                        
                        
                        fluidRow(
                          column (3,offset = 1,
                                  br(), #hr()
                                  useShinyjs(),
                                  extendShinyjs(text = jscode),
                                  actionButton("refresh", "refresh", icon("paper-plane"), 
                                               style="color: #fff; background-color: #7fbf7f; border-color: #2e6da4", width = 150)
                          ))
                        
                      )),
                    
                    
                    dashboardBody(
                      tags$head(
                        tags$link(rel = "stylesheet", type = "text/css", href = "custom.css")
                      ),
                      tags$style(type="text/css",
                                 ".shiny-output-error { visibility: hidden; }",
                                 ".shiny-output-error:before { visibility: hidden; }"
                      ),
                      tabItems(
                        
                        # First tab content
                        tabItem(tabName = "MAP",
                                fluidRow(
                                  tabBox(
                                    height = 750, width = 950, selected = tags$b("Monitoring station"),
                                    tabPanel(
                                      tags$b("Monitoring station"), leafletOutput('myMap_all', height = 650, width = 750)
                                    )
                                    # tabPanel(
                                    #   tags$b("Site Station"), leafletOutput('myMap', height = 650, width = 750)
                                    # )
                                  )
                                )),
                        
                        
                        
                        # Second tab content
                        tabItem(tabName = "Stats",
                                fluidRow(
                                  tabBox(
                                    height = 750, width = 350, selected = tags$b("Daily Averages"),
                                    tabPanel(
                                      tags$b("Daily Averages"), DT::dataTableOutput('stats_all', width = "100%")
                                    ),
                                    # tabPanel(
                                    #   tags$b("Daily Averages_b"), DT::dataTableOutput('statss')
                                    # ),

                                    tabPanel(
                                      tags$b("Time Series and Z-SCORE"), 
                                      box(title = " ", height = 750, width = 550, dygraphOutput("mean_dygraphs", width = "100%", height = "200px"),
                                                                                  dygraphOutput("z_score_dygraphs", width = "100%", height = "200px"))
                                    )
                                  )
                                ))
                        
                        
                        
                        # tabItem(tabName = "Add_Stuff",
                        #         fluidRow(
                        #           tabBox(
                        #             height = 750, width = 950, selected = tags$b("Data"), 
                        #             tabPanel(
                        #               tags$b("Data"), tableOutput('subsectors')
                        #             ),
                        #             tabPanel(
                        #               tags$b("Summary_plot"),
                        #               column(3, plotlyOutput("subsectors_plot", height = "700px", width = "850px"))
                        #             )
                        #           )
                        #         ))
                      ))
)